Implement a script-plugin to use Detekt for Kotlin code analsysis
SpineEventEngine/config pull request #420
Opened 2022-10-27 13:58 UTC by yevhenii-nadtochii

This changeset implements `detekt-code-analysis` script-plugin. This plugin adds `detekt` Gradle task that is bound to `check` task. The task runs `detekt` analyzer upon Kotlin sources.

In this PR, only the most basic configuration of Detekt is performed. It excludes `*Test.kt` and `*Spec.kt` files for some rules.

## Breaking change

Presence of Detekt on a classpath of `buildSrc` breaks fully-qualified accessors to our dependency-objects from `plugins` section. Thus, plugins can only be applied by string ID. See [issue](https://github.com/gradle/gradle/issues/22532).

For example, the original `plugins` section from `base` repository:

```kotlin
plugins {
    // ...
    with(io.spine.internal.dependency.Protobuf.GradlePlugin) { id(id) }
    with(io.spine.internal.dependency.ErrorProne.GradlePlugin) { id(id) }
}
```

Becomes the following:

```kotlin
plugins {
    // ...
    id("com.google.protobuf") // io.spine.internal.dependency.Protobuf.GradlePlugin
    id("net.ltgt.errorprone") // io.spine.internal.dependency.ErrorProne.GradlePlugin
}
```

2022-10-27 14:39 UTC, yevhenii-nadtochii commented
@alexander-yevsyukov Please take a look.

2022-10-27 17:33 UTC, armiol requested changes

2022-10-27 17:33 UTC, armiol commented on buildSrc/src/main/kotlin/detekt-code-analysis.gradle.kts
> + * After apply, Detekt is configured to use `${rootDir}/config/quality/detekt-config.yml` file.
"Applying" or "application".

2022-10-27 17:33 UTC, armiol commented on buildSrc/src/main/kotlin/detekt-code-analysis.gradle.kts
> + * In order to totally substite it, just overwrite the corresponding property:
"substitute". 

Please have another proofread run.

2022-10-28 09:36 UTC, yevhenii-nadtochii commented
@armiol @alexander-yevsyukov PTAL.

I've updated the PR description to include a finding from this [prototype](https://github.com/SpineEventEngine/base/pull/756).

I don't see other options to set up Detekt from `buildSrc` without its presence on the classpath. Groovy Interop can't be used to apply a published plugin with a version from a script-plugin. I just remembered a similar [situation](https://github.com/SpineEventEngine/config/issues/298), when it wasn't possible to obtain a typed plugin on the classpath. But in that case, Grovvy Interop managed to solve the problem, as the requested plugin was meant to be applied in advance.

2022-10-28 09:38 UTC, armiol approved these changes

2022-10-28 09:41 UTC, merged