Add `todo` live template
SpineEventEngine/config pull request #431
Opened 2022-11-02 14:12 UTC by yevhenii-nadtochii

2022-11-02 14:28 UTC, yevhenii-nadtochii commented
@alexander-yevsyukov Please take a look. Is this approach viable?

2022-11-02 14:32 UTC, armiol reviewed
@yevhenii-nadtochii 
Please see this: https://github.com/SpineEventEngine/documentation/wiki/IntelliJ-IDEA-configuration#live-templates

2022-11-02 14:38 UTC, armiol commented
@yevhenii-nadtochii and this: https://sites.google.com/a/teamdev.com/engineers/development-standards/java/style-guide/todo-comments

2022-11-02 15:40 UTC, alexander-yevsyukov commented on .idea/live-templates/todo.xml
> +    <option name="KOTLIN" value="true" />
We need JavaScript and Dart too.

2022-11-02 15:41 UTC, alexander-yevsyukov commented on .idea/live-templates/todo.xml
> +    <option name="KOTLIN" value="true" />
Sometimes it is needed in HTML.

2022-11-02 15:41 UTC, alexander-yevsyukov commented on .idea/live-templates/todo.xml
> +    <option name="KOTLIN" value="true" />
And Markdown.

2022-11-02 15:58 UTC, alexander-yevsyukov reviewed
Please see my comments and questions.

2022-11-02 15:58 UTC, alexander-yevsyukov commented on quality/detekt-config.yml
>      maxLineLength: 120
I think, we have 100 in our code. Don't we?

2022-11-02 17:31 UTC, yevhenii-nadtochii commented
@alexander-yevsyukov Please take another look. 

I've dropped context restrictions at all. IDEA will try to find the appropriate `commendStart` and `commentEnd` symbols on its own. It works correctly for all mentioned languages, besides Markdown. It officially doesn't have comments at all, and they are simulated with a [hack](https://www.jetbrains.com/help/idea/markdown.html#comments). In our case, IDEA returns nothing for `commentEnd()` function in Markdown documents, producing a comment without a closing parenthesis. It's not a big penalty taking into account, we would have a single template.

2022-11-02 17:56 UTC, yevhenii-nadtochii commented
And, as far as I understand, @armiol suggested putting this `todo.xml` along with `spine.xml` (on Google Drive) and update a dedicated section in Wiki of `documentation` repo?

2022-11-02 18:19 UTC, alexander-yevsyukov approved these changes
LGTM

2022-11-02 21:24 UTC, alexander-yevsyukov commented
> And, as far as I understand, @armiol suggested putting this `todo.xml` along with `spine.xml` (on Google Drive) and update a dedicated section in Wiki of `documentation` repo?

As I understood, Alex gave links to the current documentation on how to arrange live templates in IDEA.

2022-11-03 08:52 UTC, armiol requested changes
Please see my comment above.

2022-11-03 12:32 UTC, yevhenii-nadtochii commented
@armiol @alexander-yevsyukov PTAL. 

I've included `Spine.xml` template group and updated the [corresponding section](https://github.com/SpineEventEngine/documentation/wiki/IntelliJ-IDEA-configuration#live-templates) in wiki. 

Although, I can't delete content from [Spine > spine.io > wiki-resources](https://drive.google.com/drive/u/0/folders/0B562RqcmJm7OZzdOeVVfZVNvNDQ?resourcekey=0-cbM2y3JqU4Gy--PlmNpdIA) Google Drive folder. I would like to delete that two files, as they are not needed anymore.

2022-11-03 12:59 UTC, armiol approved these changes

2022-11-03 13:04 UTC, merged